### ISSUE TITLE
store UAST dataset in a way suitable for multiple forks and references

### ISSUE THREAD

**Issue by smola** [src-d/berserker#20]
This is the proposal for new datasets structure:

## repositories

* init_hash sha1 (partition key)
* repository_id ulid
* reference string
* commit_hash sha1
* is_main_repository bool: this is true if we detected the repository as main repository in a fork network

## files

* init_hash sha1 (partition key)
* commit_hash sha1
* blob_hash sha1
* path string
* language string

## UASTs

* language string (partition key)
* init_hash sha1 (partition key)
* blob_hash sha1
* uast []byte (protobuf-encoded)

**Comment by smola** [comment]
The new proposal is avoiding an external extractor:
* ship `siva` and `enry` binaries with the jar
* implement everything in the Scala side with `jgit`
* call external commands `siva unpack` and `enry` (taking file as stdin?) as needed #21 

We don't need to query the database. This can be done just lookin at every siva file.

**Comment by bzz** [comment]
If I'm not mistaken, we are talking about .parquet dataset, right?

> We don't need to query the database. 

This design goal sounds really good.  

A bit pity that we did not take this into account in previous sprint, while working on initial Berserker - that might save quite some time. 

If i'm reading it right, the idea would be to have Spark job that:
 - for each .siva file in HDFS
 - copies it to local FS
 - call `siva unpack`
 - using jgit, iterates all HEAD refs of original repos
 - for every file 
 - detects language with `enry` (assume STDIO is used to avoid working on gRPC streaming)
 - `bblfsh_client.Parse()` for file -> UAST extraction using bblfsh server
 - saves the results as 3 `DataFrames`, serialized to `.parquet` 
 - these 3 datasets would be suitable for SparkSQL joins, in order to get things like "all UASTS in python and java for all files in all repos at HEAD"

3 questions on proposal:

  0. On `ship siva and enry binaries with the jar` - this would imply making releases binaries of go-siva and enry for multiple platforms, right? That sounds good and there already is src-d/enry#74

  1. Would this make changes on Borges side mandatory first, in order to store the original repository refs inside rooted repositories (AKA src-d/borges#74) ? Or would there be another way of picking original repository from Rooted ones?

  2. Stateless simplicity of this approach is great, but would this imply forking at least 2 new OS process from Spark worker JVM? One with `enry` derivative #21 (per-partition/N-rooted-repos?) and one with `siva` (per-rooted-repo)? Two possible performance implications here:
      - Time: minor, but every OS processes has startup time
      - Heap: AFAIK on *nix systems `fork()` creates a process with the same memory size as parent, and so that would increase peak RAM usage like `spark.executor.memory` x3.  

        Last time I checked PySpark,  there was a special trick with daemon process to avoid that, as they start a new Python process per task. (More details in https://cwiki.apache.org/confluence/display/SPARK/PySpark+Internals section "Daemon for launching worker processes")
      
After understanding better the details above, I'll be happy to make a very quick draft of Design Document with all these information for a new iteration of work on Berserker.

**Comment by ajnavarro** [comment]
@bzz You understood totally right all the steps that we will need to change berserker approach

About https://github.com/src-d/borges/issues/74 , is not needed, we are saving ids instead of urls into our parquet representations. Can be an improvement for next iterations.

The issue that we need to check if it's happening is this one: https://github.com/src-d/borges/issues/116. Then, getting all the references with a pattern like `refs/origin/HEAD/%repoID` and process it.

Good point about several binaries for every OS, we will need to add at least linux and MACOS, and choose the correct binary in each case.

About 2: Do we have a better way to uncompress siva files using JVM?

**Comment by bzz** [comment]
Thanks for your explanation!

0. took a liberty of filing src-d/go-siva#16
1. Got it. This would not allow ast2vec to use .parquet files as-is, but looks like we are ok with it.
2. We need to think about it.
    I.e we could have servers for `enry` and `siva` which process lifecycle is managed outside of Spark, same as for bbflsh server. But AFAIK the design of #21 would not permit it for `enry` \wo better IPC (i.e gRPC)

From discussion with @ajnavarro - seems like we need a design document with bigger scope then only for Berserker. It should include not just iterating files in repos skipping forks, but also how this fits into parallelization of actual pre-processing for ast2vec and the implications it has for write side of pipeline in Borges/Rovers (like src-d/borges#117 and src-d/rovers#144)

**Comment by bzz** [comment]
Here is a first version of berserker design document, that incorporates the schema proposal from above as well as discussion from #21 

https://docs.google.com/document/d/1Arf2siiol94YkOCHfBqlweUKU2gYsfBbyCs9pRzHhUs/edit#heading=h.312llb206ety

**Comment by smola** [comment]
@bzz For the binaries, I wouldn't go too far with shipping binaries for multiple OS and architectures. We can always a) fallback to a environment variables `SIVA_BIN_PATH` and `ENRY_BIN_PATH` to get binary paths or provide a way and/or b) provide a way to build berserker embedding alternative binaries.

**Comment by smola** [comment]
With respect to the performance of launching binaries:

* if startup time is a problem, we can maintain the external binaries alive and pipeline all the requests without restarting before requests. We have used this approach in bblfsh which works quite well.
* wrt memory usage, I think OpenJDK 8 uses `vfork` on Linux and this is not a problem anymore, but if there are still problems with that, we can look for some workaround.

**Comment by bzz** [comment]
#23 has the pure Scala implementation UAST extraction

Few more things related to this were extracted to #24 #25 #26 #27 #28 #29 #30 #31

**Comment by bzz** [comment]
Closing due to #38
