### ISSUE TITLE
create language detector using enry

### ISSUE THREAD

**Issue by smola** [src-d/berserker#21]
Language detection binary in Go suitable to call form Scala as an external process.
It will take the file name as argument and it will output the language to stdout. If it needs the conents, it will print `NEED_CONTENT` to stdout, then the caller will write file content to stdin and then check stdout for the language.

**Comment by bzz** [comment]
3 questions, before we implement this 
 - would not STDIN/STDOUT IPC make language detection process inherently non-concurrent for all the clients and is overall design ok with that?
 - why STDIN/STDOUT is used in favor of gRPC here?
 - how error handing will be implemented between client and this binary?
   I.e when something happened to Enry process and it could not detect lang or input is too big, etc how this will be communicated to a client?

**Comment by mcarmonaa** [comment]
@bzz The language detection won't be a process running always as a service, It will be launched from scala when needed and connected by a pipe, so gRPC is not necessary and you get concurrency from scala side I guess.

About error handling, It can return just `ERROR` by the moment. What do you think?

**Comment by ajnavarro** [comment]
We can use non-zero error numbers, as many other scripts.

**Comment by bzz** [comment]
I see, thank you for explanations, guys!

2 things:
 - would not this non-concurrent blocking IPC design would limit our ability to deal with i.e OS processes memory peak usage, as discussed in https://github.com/src-d/berserker/issues/20#issuecomment-316849093 ?
 -  `It can return just ERROR` it's a separate OS process, so could you elaborate where do you suggest to return it?

So please help me understand how a client for this IPC will look like:

 0. fork() new `enry` process
 1. write filename to STDIN
 2. loop on reading from STDOUT, until `<something>` (EOL?) or STDOUT is closed
 3. if `NEED_CONTENT ` is read:
    - read file, write it to STDIN
    - loop on reading from STDOUT, until `<something>` or STDOUT is closed
 4. else return what's read
 5. if STDOUT is closed (in any of above)
    - read from `<somewhere>` a non-zero error code
    - return error, from `Map<exit-code, "user friendly message">`
 6. SIGTERM `enry`

With gRPC these 10s of LOC would be replaced by basically 2-3 lines of calling to generated code, as well as give ability to have non-blocking client APIs, and provide more control of process lifecycle (ability use as a service).

Sorry if that is something obvious, may be I'm missing something here i.e a background assumptions this IPC design is optimizing for? What are the advantages of it?

**Comment by bzz** [comment]
After more thinking: managing a process lifecycle, IPC though STDIO and `NEED_CONTENT` part of this new protocol (which presumably is an optimization, to avoid extra file reading) will add complexity to the Berserker on file language detection task. 

At the same time - Berserker already is sending full file content and name to the bblfsh server through convenient gRPC protocol, and server has `enry` lib linked in. 

Would not it make more sense to add new RPC endpoint to bblfsh server instead of that?
Something similar to this pseudo-code:
```go
DetectLanguage(filename) (string, err) //err can be of ErrContentNeeded type to condition on that
DetectLanguageByContent(filename, []byte) string
ParseAndDetectLanguage(/*same as Parse*/) (string, UAST)
```

This would save time:
 - no need for new extra binary
 - no need for new process lifecycle management
 - no need to new custom IPC implementation
 - without compromising the same kind of possible optimization on skipping reading files

The only downside I can see right now - coupling of lang detection and UAST extraction on Babelfish side API, which is easily mitigated by adding separate language detection gRPC endpoints (DetectLanguage* from above) to bblfsh server, to support optimization similar to `CONTENT_NEEDED`.

This does not push complexity from one side (berserker) to another (bblfhs), but rather propose  how to completely avoid unnecessary accidental complexity, leveraging already settled nature of bbfsh<->berserker interaction and their roles.

@smola @mcarmonaa @ajnavarro @abeaumont Please, let me know what you guys think!

**Comment by mcarmonaa** [comment]
@bzz maybe you need to send a file to bblfsh server depending on the file's language, so you need to detect language before connect to bblfsh.

Right now, we only need UASTs from java and python files, so if you can do language detection on no java/python files without read these files and know that they don't have to be sent to bblfsh server, you will save a lot of time.

I think this is the main point to do this task.

**Comment by bzz** [comment]
@mcarmonaa good point, that is exactly what we do in Berserker right now.

> adding separate language detection gRPC to bblfsh server

sorry if that was not clear, but what I meant by this was a suggestion to add 2 new methods to bblfsh server
 - `DetectLanguage(filename)`
 - `DetectLanguageByContent(filename, []byte)`

So the flow in Berserker would look like

```go
lang := bblfsh_client.DetectLanguage(filename)
if  lang is not detected { // such files can be skipped, if we want to be really fast
 lang := bblfsh_client.DetectLanguageByContent(filename, fullFileContent)
}

if lang == "python" || lang == "java" {
  // read fullFileContent, if not already read above
  lang := bblfsh_client.Parse(filename, lang, fullFileContent)
}
```

Please let me know if that helps to understand my suggestion better. The comment above was also updated.

**Comment by mcarmonaa** [comment]
Oh I see, thanks for the clarification @bzz.

**Comment by abeaumont** [comment]
@bzz I don't think this is a feature `bblfsh server` should provide, since it's a parser. It provides a language autodetection as a fallback, but not something you'd want to expose (think of GCC, you can set the language explicitely with `-x` or autodetect based on extension by default, but it doesn't provide a command to give the language of a file). So if you want a language detection service instead of directly calling enry, I think it's better to build a specific server for that.

**Comment by bzz** [comment]
@abeaumont thanks, really appreciate thoughtful feedback and an example! Language detection server sound as a good alternative. Could even make sense to keep if as OSS under src-d/enry codebase, as a separate build target.

I agree with this from a general point of view. Although I must admit, in the retrieval pipeline context, it seems quite tempting to avoid operational overhead of having to deploy 1 more extra process.

@mcarmonaa 
> So do you think it's more expensive spawn a process than go through all the network protocol stack?

I believe such performance implications were not part of the discussion so far. There was some discussion on Heap overhead of forking processes from JVM in #20 though.

What I did propose, was:
 - do not spend time on implementing IPC though STDIO as it complicates things without a good reason
 - re-use PRC approach that we are already using in other parts of the system (gRPC server/client)

Or did I miss-understand, and you are asking if we should change Bblfsh server to use STDIO IPC in Berserker, in order to avoid networking stack overhead?

**Comment by mcarmonaa** [comment]
@bzz, No, I was not asking that, I was just talking about language detection. Sorry for my confusion, I don't know much about spark and all the pipeline aspects yet, so I'm trying to learn all those things

**Comment by smola** [comment]
I think it's a good idea. I have no objections either way, so what @bzz says ;)

**Comment by bzz** [comment]
Further discussion as well as particular gRPC interface proposal moved to https://github.com/src-d/berserker/pull/22#issuecomment-317393226

**Comment by bzz** [comment]
Awesome work, thank you guys!

Closing as #22 was merged now
